### ISSUE TITLE
CSS방법론: BEM 문제제의

### ISSUE THREAD

**Issue by Dseok12** [Bigdooor-studycourse/SSAC-community#22]
클래스 네임이 길어짐으로 인한 가독성의 문제점.
조속한 수정이 필요해보임

PS. find_user.html 및 find_user.scss파일의 class 참고바랍니다.

**Comment by DawonJeon** [comment]
Suggestion : 클래스 가독성을 향상시키기 위해서 "개인이 맡은 파일명__element"로 변경을 제의합니다.
'BEM' 방법론은 하나의 '방법'이지 '정답'은 아니니, 작업의 효율성을 위해서 클래스명 정리가 필요할 듯 합니다. 
또한, 몇몇의 파일은 파일명에 공백이 있으면 _(언더바 1개)를 삽입하여 ex) my_page, find_user
파일명과 element의 구분이 잘 되지 않아 오히려 혼란이 가중되니  ex) my_page_input
elment와 파일명의 확실한 구분을 위하여 파일명 뒤에 __ (언더바2개)를 추가하면 어떠실지요? ex) my_page__input
(혹은 파일명에 있는 공백을 언더바가 아닌 -(하이픈) 처리가 더욱 효율적일듯 합니다) ex) my-page__input

**Comment by VeryverySoHappy** [comment]
저도 DawonJeon님의 의견에 동의합니다.
'파일명__(자신이 하고싶은)클래스명'으로 하는 것이 가독성이 더 좋아보입니다.
