### ISSUE TITLE
"Design: header.html, css 추가": css파일 재확인 요청 

### ISSUE THREAD

**Issue by DawonJeon** [Bigdooor-studycourse/SSAC-community#24]
"Design: header.html, css 추가"

scss파일이 잘못 전송되었음
input태그의 id값이 html의 id값과 일치하지 않습니다.

**Comment by VeryverySoHappy** [comment]
Design: _header.scss, index.html수정, index.scss에 _header.scss 추가

_header.scss파일과 index.html수정하였습니다.
.index.scss에 _header.scss추가하였습니다.
